practice_TrekCompany/Controllers/BikeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using practice_TrekCompany.Data;
using practice_TrekCompany.Models.production;

namespace practice_TrekCompany.Controllers
{
    public class BikeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BikeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Bike> bikes = _context.Bikes
                .Include(a => a.TypeOfBike).ToList();
            return View(bikes);
        }

        public IActionResult Detail(int id)
        {
            Bike bike = _context.Bikes
                .Include(a => a.Wheelset.Rim)
                .Include(a => a.Wheelset.Hub)
                .Include(a => a.Wheelset.Tire)
                .Include(a => a.Frameset.Frame)
                .Include(a => a.Frameset.Fork)
                .Include(a => a.Groopset.Transmition.Cassette)
                .Include(a => a.Groopset.Transmition.Switch)
                .Include(a => a.Groopset.Transmition.Shifter)
                .Include(a => a.Groopset.Transmition)
                .Include(a => a.Groopset.Pedals)
                .Include(a => a.Groopset.Carriage)
                .Include(a => a.Equipment.Brake)
                .Include(a => a.Equipment.Grips)
                .Include(a => a.Equipment.Handlebar)
                .Include(a => a.Equipment.Saddle)
                .Include(a => a.Equipment.SeatPost)
                .Include(a => a.Equipment.Steering)
                .Include(a => a.Equipment.Stem)
                .Include(a => a.TypeOfBike)
                .FirstOrDefault(c => c.BikeId == id);
            return View(bike);
        }
    }
}

practice_TrekCompany/Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using practice_TrekCompany.Data;
using practice_TrekCompany.Models.factory;

namespace practice_TrekCompany.Controllers
{
    public class StaffController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StaffController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            List<Staff> staff = _context.Staffs
                .Include(a => a.Factory)
                .Include(a => a.JobTitle).ToList();
            return View(staff);
        }
    }
}

practice_TrekCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - practice_TrekCompany</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/practice_TrekCompany.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <p class="navbar-brand">practice_TrekCompany</p>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bike" asp-action="Index">Bikes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Staff</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spares" asp-action="Index">Spares</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - practice_TrekCompany 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>